### ISSUE TITLE
Attempt to add with overflow

### ISSUE THREAD

**Issue by fuwx295** [polarsignals/rust-jemalloc-pprof#4]
# Describe the bug
There was an overflow in the fetch memory heap file.
![image](https://github.com/polarsignals/rust-jemalloc-pprof/assets/88039311/8c135599-20b5-4bc8-941d-1f52311b09e6)
# How to reproduce?
1. download rust-jemalloc-pprof
![image](https://github.com/polarsignals/rust-jemalloc-pprof/assets/88039311/e7e389f4-76a2-45c1-9a56-bbabe967eb70)
2. build & run
![image](https://github.com/polarsignals/rust-jemalloc-pprof/assets/88039311/248c0120-95aa-4073-8676-3f48b082272e)
# What did you expect to see?
Successfully fetching files from profiling memory
# What did you see instead?
reply empty
![image](https://github.com/polarsignals/rust-jemalloc-pprof/assets/88039311/51416d66-f006-4d8c-9855-121fcf6bbb12)
attempt to add with overflow
![image](https://github.com/polarsignals/rust-jemalloc-pprof/assets/88039311/2ce8c4f3-3ef1-405b-9f67-9624aedb16f9)
# Environment (please complete the following information)
![image](https://github.com/polarsignals/rust-jemalloc-pprof/assets/88039311/515076dc-234c-43bb-94a0-4f03b4fb1fb4)

**Comment by umanwizard** [comment]
Hi @fuwx295 , I have pushed a commit that should fix this issue. Please try again with the latest `main`.

**Comment by fuwx295** [comment]
> Hi @fuwx295 , I have pushed a commit that should fix this issue. Please try again with the latest `main`.

Received, thanks! Everything is back to normal now. Thanks for your help!
